---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pr-pipeline
spec:
  params:
    - name: target-repository
      description: the git repo
    - name: target-branch
      description: the branch for the git repo
    - name: pr-repository
      description: The source git repo for the PullRequest
      default: ""
    - name: pr-branch
      description: The source branch for the PullRequest
      default: ""
    - name: pr-commit-id
      description: the commit id/sha for the PullRequest
      default: ""
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: context
      default: "unit tests"
    - name: description
      default: "Unit tests passed"
  workspaces:
    - name: pipeline-ws

  tasks:
    - name: set-git-commit-pending
      taskRef:
        name: git-set-commit-status
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(params.target-repository)
        - name: revision
          value: $(params.pr-commit-id)
        - name: context
          value: $(params.context)
        - name: description
          value: $(params.description)
        - name: state
          value: "pending"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: git-clone
      taskRef:
        name: git-clone-repo
      params:
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "apikey"
        - name: repository
          value: $(params.target-repository)
        - name: branch
          value: $(params.target-branch)
        - name: pr-repository
          value: $(params.pr-repository)
        - name: pr-branch
          value: $(params.pr-branch)
        - name: pr-revision
          value: $(params.pr-commit-id)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: unit-tests
      runAfter: [git-clone]
      taskRef:
        name: tester-run-tests
      params:
        - name: tests-script
          value: |
            if [ -f ./test/run-tests.sh ]; then
              source ./test/run-tests.sh
            else
              echo "Test runner script not found: ./test/run-tests.sh"
            fi
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
  finally:
    - name: set-git-commit-status
      taskRef:
        name: git-set-commit-status
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(params.target-repository)
        - name: revision
          value: $(params.pr-commit-id)
        - name: context
          value: $(params.context)
        - name: description
          value: $(params.description)
        - name: state
          value: "$(tasks.unit-tests.status)"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
