version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: secure-lock-kubernetes.svg
  required:
    - build
    - repo
  info:
    git url: >-
      [https://github.com/open-toolchain/secure-kube-toolchain](https://github.com/open-toolchain/secure-kube-toolchain)
    git branch: >-
      [master](https://github.com/open-toolchain/secure-kube-toolchain/tree/master)
toolchain:
  name: 'kube-toolchain-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted"
services:
  repo:
    $parameter: 'source_provider'
    $default: 'hostedgit'
    $options:
      - $ifdef: 'hostedgit'
        service_id: hostedgit
        parameters:
          repo_name: 'BYOC MyApp'
          repo_url: '{{app_repo}}'
          type: 'link'
          has_issues: true
          enable_traceability: true
      - $ifdef: 'githubpublic'
        service_id: githubpublic
        parameters:
          repo_name: 'BYOC MyApp'
          repo_url: '{{app_repo}}'
          type: 'link'
          visibility: public
      - $ifdef: 'github_integrated'
        service_id: github_integrated
        parameters:
          repo_name: 'BYOC MyApp'
          repo_url: '{{app_repo}}'
          type: 'link'
          has_issues: true
          enable_traceability: true
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          GIT_REPO: repo
          CF_APP_NAME: '{{form.pipeline.parameters.app-name}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          PROD_RESOURCE_GROUP: '{{form.pipeline.parameters.prod-resource-group}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
          PROD_CLUSTER_NAMESPACE: '{{form.pipeline.parameters.prod-cluster-namespace}}'
        execute: true
  webide:
    service_id: orion
form:
  pipeline:
    parameters:
      app-name: '{{services.repo.parameters.repo_name}}'
      prod-cluster-namespace: prod
    schema:
      $ref: deploy.json
