---
apiVersion: tekton.dev/v1
kind: EventListener
metadata:
  name: github-pr-listener
  annotations:
    tekton.dev/displayName: "github pull-request listener"
spec:
  triggers:
    - bindings:
        - name: github-pr-binding
      template:
        name: pr-template
---
apiVersion: tekton.dev/v1
kind: EventListener
metadata:
  name: gitlab-pr-listener
  annotations:
    tekton.dev/displayName: "GRIT/gitlab merge-request listener"
spec:
  triggers:
    - bindings:
        - name: gitlab-pr-binding
      template:
        name: pr-template
