---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pr-pipeline
spec:
  params:

    - name: branch
      description: branch
    - name: revision
      description: the git revision/commit for the git repo
      default: ""
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: pr-url
      description: pr url
    - name: repository
      description: the git repo containing source code. If empty, the repository url will be found from toolchain
      default: ""
    - name: commit-timestamp
    - name: scm-type
    - name: project-id
      default: ""
  workspaces:
    - name: pipeline-ws

  tasks:
    - name: extract-repository-url
      taskRef:
        name: toolchain-extract-value
      params:
        - name: expression
          # if a params.repository is given, it takes precedence
          value: '. as $toolchain | ["$(params.repository)"] | if .[0]=="" then $toolchain | .services[] | select(.toolchain_binding.name=="repo") | .dashboard_url else .[0] end'
        - name: pipeline-debug
          value: $(params.pipeline-debug)  
    - name: git-clone
      taskRef:
        name: git-clone-repo
      params:
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "apikey"
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
        - name: branch
          value: $(params.branch)
        - name: revision
          value: $(params.revision)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: unit-tests
      runAfter: [git-clone]
      taskRef:
        name: tester-run-tests
      params:
        - name: tests-script
          value: |
            if [ -f ./tests/run-tests.sh ]; then
              source ./tests/run-tests.sh
            else
              echo "Test runner script not found: ./tests/run-tests.sh"
            fi
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
    - name: cra-discovery-scan
      runAfter:
        - git-clone
      taskRef:
        name: cra-discovery
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
        - name: revision
          value: $(params.branch)
        - name: commit-id
          value: $(tasks.git-clone.results.git-commit)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: directory-name
          value: ""
        - name: commit-timestamp
          value: $(params.commit-timestamp)
    - name: code-detect-secrets-status-pending
      runAfter:
        - git-clone
      taskRef:
        name: git-set-commit-status
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: state
          value: pending
        - name: description
          value: "Tekton PR Pipeline Status"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: context
          value: "Vulnerability scan"
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
    - name: code-vulnerability-scan
      runAfter:
        - cra-discovery-scan
      taskRef:
        name: cra-vulnerability-remediation
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
        - name: secrets
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
        - name: revision
          value: $(params.branch)
        - name: pr-url
          value: $(params.pr-url)
        - name: commit-id
          value: $(tasks.git-clone.results.git-commit)
        - name: scm-type
          value: $(params.scm-type)
        - name: project-id
          value: $(params.project-id) 
    - name: code-vulnerability-scan-status-finished
      runAfter:
        - code-vulnerability-scan
      taskRef:
        name: git-set-commit-status
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
        - name: state
          value: "$(tasks.code-vulnerability-scan.results.status)"
        - name: context
          value: "Vulnerability scan"
        - name: description
          value: "Tekton PR Pipeline Status"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: code-cis-scan-status-pending
      runAfter:
        - git-clone
      taskRef:
        name: git-set-commit-status
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: state
          value: pending
        - name: description
          value: "Tekton PR Pipeline Status"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: context
          value: "CIS scan"
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
    - name: cra-cis-check
      taskRef:
        name: cra-cis-check
      runAfter:
        - cra-discovery-scan
      workspaces:
        - name: secrets
          workspace: pipeline-ws
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
        - name: revision
          value: $(params.branch)
        - name: pr-url
          value: $(params.pr-url)
        - name: commit-id
          value: $(tasks.git-clone.results.git-commit)
        - name: directory-name
          value: ""
        - name: scm-type
          value: $(params.scm-type)
        - name: project-id
          value: $(params.project-id)
    - name: code-cis-scan-status-finished
      runAfter:
        - cra-cis-check
      taskRef:
        name: git-set-commit-status
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: state
          value: "$(tasks.cra-cis-check.results.status)"
        - name: description
          value: "Tekton PR Pipeline Status"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: context
          value: "CIS scan"
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
    - name: code-bom-check-status-pending
      runAfter:
        - git-clone
      taskRef:
        name: git-set-commit-status
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: state
          value: pending
        - name: description
          value: "Tekton PR Pipeline Status"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: context
          value: "BOM check"
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
    - name: cra-bom
      taskRef:
        name: cra-bom
      runAfter:
        - cra-discovery-scan
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
        - name: secrets
          workspace: pipeline-ws          
      params:
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
        - name: revision
          value: $(params.branch)
        - name: pr-url
          value: $(params.pr-url)
        - name: commit-id
          value: $(tasks.git-clone.results.git-commit)
        - name: target-branch
          value: $(params.branch)
        - name: target-commit-id
          value: $(tasks.git-clone.results.git-commit)      
        - name: scm-type
          value: $(params.scm-type)
        - name: project-id
          value: $(params.project-id)
    - name: code-bom-check-status-finished
      runAfter:
        - cra-bom
      taskRef:
        name: git-set-commit-status
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
      params:
        - name: state
          value: "$(tasks.cra-bom.results.status)"
        - name: description
          value: "Tekton PR Pipeline Status"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: context
          value: "BOM check"
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
