---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: secure-kube-pr-pipeline
spec:
  params:
    - name: ibmcloud-api
      description: The ibmcloud api
    - name: git-token
      description: access token for the git repo
    - name: pipeline-debug
      description: Toggles debug mode for the pipeline

    # Event params
    - name: branch
      description: The git branch
    - name: commit-id
      description: commit id
    - name: pr-branch
      description: The branch in the forked git repo from where the PR is made
    - name: pr-repository
      description: The forked git repo from where the PR is made
    - name: repository
      description: The git repo

    - name: build-script
      description: The command(s) to run the build in run-build step. It will override the default commands
      default: ""
    - name: toolchain-build-image
      description: Image to use for `build` task
      default: "icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.79"
    - name: tester-tests-image
      description: Image to use for `unit-test` task
      default: "icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.79"

  workspaces:
    - name: artifacts

  tasks:
    - name: extract-repository-url
      taskRef:
        name: toolchain-extract-value
      params:
        - name: expression
          # if a params.repository is given, it takes precedence
          value: '. as $toolchain | ["$(params.repository)"] | if .[0]=="" then $toolchain | .services[] | select(.toolchain_binding.name=="repo") | .dashboard_url else .[0] end'
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: git-clone
      taskRef:
        name: git-clone-repo
      params:
        - name: branch
          value: $(params.branch)
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-api
          value: $(params.ibmcloud-api)
        - name: ibmcloud-apikey-secret-key
          value: "apikey"
        - name: git-access-token
          value: $(params.git-token)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: pr-branch
          value: $(params.pr-branch)
        - name: pr-repository
          value: $(params.pr-repository)
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
        - name: revision
          value: $(params.commit-id)
      workspaces:
        - name: output
          workspace: artifacts
    - name: build
      runAfter: [git-clone]
      taskRef:
        name: toolchain-build
      params:
        - name: run-build-image
          value: $(params.toolchain-build-image)
        - name: custom-script
          value: $(params.build-script)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
      workspaces:
        - name: output
          workspace: artifacts
    - name: unit-tests
      runAfter: [build]
      taskRef:
        name: tester-run-tests
      params:
        - name: tests-image
          value: $(params.tester-tests-image)
        - name: tests-script
          value: |
            if [ -f ./test/run-tests.sh ]; then
              source ./test/run-tests.sh
            else
              echo "Test runner script not found: ./test/run-tests.sh"
            fi
      workspaces:
        - name: artifacts
          workspace: artifacts

