---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pr-template
spec:
  params:
    - name: target-branch
      description: target branch
    - name: target-commit-id
      description: target commit id
    - name: target-repository
      description: the repo integration name
    - name: pr-repository
      description: PR repository
    - name: pr-branch
      description: branch
    - name: pr-commit-id
      description: commit id
    - name: pr-commit-timestamp
      description: commit timestamp
    - name: pr-url
    - name: scm-type
      description: source code type used (github, github-ent, gitlab)
    - name: project-id
      description: project id
      default: ""
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pr-pipeline
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: target-repository
            value: $(params.target-repository)
          - name: target-branch
            value: $(params.target-branch)
          - name: target-commit-id
            value: $(params.target-commit-id)
          - name: pr-repository
            value: $(params.pr-repository)
          - name: pr-branch
            value: $(params.pr-branch)
          - name: pr-commit-id
            value: $(params.pr-commit-id)
          - name: pr-commit-timestamp
            value: $(params.pr-commit-timestamp)
          - name: pr-url
            value: $(params.pr-url)
          - name: scm-type
            value: $(params.scm-type)
          - name: project-id
            value: $(params.project-id) 
          - name: pipeline-debug
            value: $(params.pipeline-debug)
