---
apiVersion: tekton.dev/v1
kind: TriggerTemplate
metadata:
  name: pr-template
spec:
  params:
    - name: apikey
      description: The ibmcloud api key
    - name: ibmcloud-api
      description: The ibmcloud api
      default: "https://cloud.ibm.com"
    - name: git-token
      description: access token for the git repo
      default: ""
    - name: pipeline-debug
      description: Toggles debug mode for the pipeline
      default: "0"
    - name: custom-image-registry-dockerconfigjson
      description: |
        dockerconfigjson for custom images used in pipeline tasks.
        See https://cloud.ibm.com/docs/devsecops?topic=devsecops-troubleshoot-devsecops#troubleshoot-pipe-abort-early
      default: "eyJhdXRocyI6e319" # ie. {"auths":{}} base64 encoded

    - name: build-script
      description: The command(s) to run the build in run-build step. It will override the default commands
      default: ""

    # Event params
    - name: branch
      description: The git branch
      default: ""
    - name: commit-id
      description: commit id
      default: ""
    - name: pr-branch
      description: The branch in the forked git repo from where the PR is made
      default: ""
    - name: pr-repository
      description: The forked git repo from where the PR is made
      default: ""
    - name: repository
      description: The git repo

    # User control params
    - name: toolchain-build-image
      description: Image to use for `build` task
      default: "icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.79"
    - name: tester-tests-image
      description: Image to use for `unit-test` task
      default: "icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.79"

  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: $(params.custom-image-registry-dockerconfigjson)
      metadata:
        name: custom-image-registry-pull-secret
      type: kubernetes.io/dockerconfigjson
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: secure-kube-pr-pipeline
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: ibmcloud-api
            value: $(params.ibmcloud-api)
          - name: git-token
            value: $(params.git-token)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: branch
            value: $(params.branch)
          - name: commit-id
            value: $(params.commit-id)
          - name: pr-branch
            value: $(params.pr-branch)
          - name: pr-repository
            value: $(params.pr-repository)
          - name: repository
            value: $(params.repository)
          - name: toolchain-build-image
            value: $(params.toolchain-build-image)
          - name: build-script
            value: $(params.build-script)
          - name: tester-tests-image
            value: $(params.tester-tests-image)
        podTemplate:
          imagePullSecrets:
            - name: custom-image-registry-pull-secret
